### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlinx.coroutines.experimental.android.HandlerContext

### ISSUE THREAD

**Issue by rizkyalfauji11** [IONsoft-Indonesia/RandomNumberAnimation#11]
java.lang.NoClassDefFoundError: kotlinx.coroutines.experimental.android.HandlerContext
        at kotlinx.coroutines.experimental.android.HandlerContextKt.<clinit>(HandlerContext.kt:29)
        at kotlinx.coroutines.experimental.android.HandlerContextKt.getUI(HandlerContext.kt:29)
        at id.co.ionsoft.randomnumberanimationlibrary.RandomNumberAnimation$InfinityTask.start$library_release(RandomNumberAnimation.kt:65)
        at id.co.ionsoft.randomnumberanimationlibrary.RandomNumberAnimation.start(RandomNumberAnimation.kt:113)
        at com.plink.mbb.fragment.main.token.PlayTokenFragment$onActivityCreated$1.onClick(PlayTokenFragment.kt:53)
        at android.view.View.performClick(View.java:4781)
        at android.view.View$PerformClick.run(View.java:19874)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5297)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by hendrawd** [comment]
Have you added `kotlin.experimental.coroutines "enable"` in your app-level build.gradle?

**Comment by hendrawd** [comment]
Since there is no update I am closing this issue
